services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
        reservations:
          cpus: "0.2"
          memory: 512M
    

volumes:
  db_data:
  