// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"hona/backend/bootstrap"
	"hona/backend/internal/infrastructure/database"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config) (*Application, error) {
	postgresDatabase := database.NewPostgresDatabase()
	wireDatabase := &Database{
		DB: postgresDatabase,
	}
	application := NewApplication(wireDatabase)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Struct(new(Database), "*"))

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
)

type Database struct {
	DB database.Database
}

type Application struct {
	Database *Database
}

func NewApplication(db *Database) *Application {
	return &Application{
		Database: db,
	}
}
